FROM node:18-alpine

# Crée le dossier de l'application
WORKDIR /app

# Copie les fichiers de dépendances
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie du code source
COPY . .

# Port exposé (modifie si ton serveur utilise autre chose que 5000)
EXPOSE 5000

# Commande de démarrage
CMD ["npm", "start"]
